---
# Install my dotfiles.
- name: Clone dotfiles repository (if it doesn't already exist).
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local_destination }}"
  sudo: no

- name: Check if .bash_profile is a link.
  shell: ls -F ~/.bash_profile
  register: is_link
  failed_when: false
  always_run: yes
  changed_when: false

- name: Remove current .bash_profile file if necessary.
  file:
    path: ~/.bash_profile
    state: absent
  when: "'@' not in is_link.stdout"

- name: Link .bash_profile into home folder.
  file:
    src: "{{ dotfiles_repo_local_destination }}/.bash_profile"
    dest: ~/.bash_profile
    state: link
  sudo: no